// export * from './Card';
export { default as Accordion } from './Accordion';
// export * from './Player';
// export * from './Profiles';
export { default as Error } from './Error';
export { default as Feature } from './Feature';
export { default as Footer } from './Footer';
// export * from './Form';
export { default as Header } from './Header';
export { default as Jumbotron } from './Jumbotron';
// export * from './Loading';
export { default as OptForm } from './OptForm';
